spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password:

server:
  port: 8081

payment:
  method:
    stripe:






    paypal:
      name: paypal
      apiUrl: https://api.paypal.com