spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password:

server:
  port: 8081

payment:
  method:
    stripe:
      name: stripe
      apiUrl: https://api.stripe.com
      timeout: 1000
      enabled: true
      supported-currencies: USD,EUR,GPB

    paypal:
      name: paypal
      apiUrl: https://api.paypal.com