spring:
  application:
    name: store

server:
  port: 8081

payment:
  method:
    stripe:
      name: stripe
      apiUrl: https://api.stripe.com
      timeout: 1000
      enabled: true
      supported-currencies: USD,EUR,GPB

    paypal:
      name: paypal
      apiUrl: https://api.paypal.com